mod 'boxen', '2.1.0', :github_tarball => 'boxen/puppet-boxen'
mod 'stdlib', '4.0.0', :github_tarball => "puppetlabs/puppetlabs-stdlib"
mod 'nodejs', '3.2.9', :github_tarball => "boxen/puppet-nodejs"
mod 'repository', '2.2.0', :github_tarball => "boxen/puppet-repository" 
